- platform: template
  lights:
    template_receiver_volume:
      friendly_name: "Receiver"
      value_template: >-
        {% if is_state('media_player.receiver', 'on') %}
          {% if states.media_player.receiver.attributes.is_volume_muted %}
            off
          {% else %}
            on
          {% endif %}
        {% else %}
          off
        {% endif %}
      icon_template: >-
        {% if is_state('media_player.receiver', 'on') %}
          {% if states.media_player.receiver.attributes.is_volume_muted %}
            mdi:volume-off
          {% else %}
            mdi:volume-high
          {% endif %}
        {% else %}
          mdi:volume-off
        {% endif %}
      turn_on:
        service: media_player.volume_mute
        data:
          entity_id: media_player.receiver
          is_volume_muted: false
      turn_off:
        service: media_player.volume_mute
        data:
          entity_id: media_player.receiver
          is_volume_muted: true
      set_level:
        service: media_player.volume_set
        data_template:
          entity_id: media_player.receiver
          volume_level: "{{ (brightness / 255 * 100)|int / 100 }}"
      level_template: >-
        {% if is_state('media_player.receiver', 'on') %}
          {{ (states.media_player.receiver.attributes.volume_level|float * 255)|int }}
        {% else %}
          0
        {% endif %}
