- platform: samsungtv
  name: TV (Stue)
  host: 192.168.0.15
  mac: !secret samsung_tv_mac
#  port: 8001

- platform: cast

- platform: onkyo
  name: Receiver
  host: 192.168.0.16
#  sources:
#    video2: GetBox II

- platform: spotify
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret
