- platform: samsungtv
  name: TV (Stue)
  host: 192.168.0.15
  mac: !secret samsung_tv_mac
#  port: 8001

- platform: cast

- platform: onkyo
  name: Receiver
  host: 192.168.0.16
  sources:
    tv-cd: TV
    video2: GetBox II
    video3: Xbox One
    video1: SNES
    video4: Aux
    video6: PC
    bd-dvd: BD/DVD
    dlna: DNLA
    network: Net

- platform: spotify
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret
