title: Home

views:
  - !include lovelace/main.yaml
  - !include lovelace/livingroom.yaml
  - !include lovelace/bedroom.yaml
  - !include lovelace/outside.yaml
  - !include lovelace/media.yaml
  - !include lovelace/system.yaml
  - !include lovelace/automations.yaml
  - !include lovelace/development.yaml
  - !include lovelace/camera.yaml
