default_view:
  name: Hjem
  view: true
  icon: mdi:home
  entities:
    - group.status
    - group.livingroom
    - group.hall
    - group.bedroom
    - group.office
    - group.storeroom
    - group.outside

climate:
  name: Klima
  view: true
  icon: mdi:temperature-celsius
  entities:
    - group.climate_control
    - group.climate_temperature
    - group.climate_humidity
    - group.climate_pressure
    - group.climate_weather
    - weather.met_no

light:
  name: Lys
  view: true
  icon: mdi:lightbulb-on
  entities:
    - group.lights
    - group.scenes
    - group.color_temp

switch:
  name: Strøm
  view: true
  icon: mdi:power-plug
  control: hidden
  entities:
    - group.switches
    - group.livingroom_heaters

security:
  name: Sikkerhet
  view: true
  icon: mdi:security
  entities:
    - group.smoke_sensors
    - group.door_windows
    - group.motion
    - group.flood_sensors
    - group.all_devices

media:
  name: Media
  view: true
  icon: mdi:television
  entities:
    - media_player.ccultra_tomlin
    - media_player.spotify
    - media_player.receiver
    - media_player.tv_stue

automation:
  name: Automations
  view: true
  icon: mdi:home-automation
  entities:
    - group.automations
    - group.notifications

other:
  name: System
  view: true
  icon: mdi:settings
  entities:
    - group.sensor_battery
    - group.sensor_signal
    - group.system
    - group.network
    - group.settings
