- platform: template
  sensors:
    template_smoke_sensor_livingroom:
      friendly_name: 'Røykvarsler'
      value_template: >-
        {% if is_state("binary_sensor.smoke_sensor_livingroom_alarm_level", "255") %}
          Alarm
        {% elif is_state("binary_sensor.smoke_sensor_livingroom_burglar", "3") %}
          Ikke montert
        {% else %}
          Standby
        {% endif %}

- platform: template
  sensors:
    template_flood_sensor_bathroom:
      friendly_name: 'Vannsensor'
      value_template: >-
        {% if is_state("binary_sensor.flood_sensor_bathroom_alarm_level", "255") %}
          Alarm
        {% elif is_state("binary_sensor.flood_sensor_bathroom_burglar", "3") %}
          Ikke montert
        {% else %}
          Standby
        {% endif %}
