- platform: yr
  monitored_conditions:
    - symbol
    - temperature
    - humidity
    - precipitation
    - windSpeed
    - windDirection
    - cloudiness
    - pressure

- platform: netatmo
  station: Home
  modules:
    - Bedroom
    - Outside
