- platform: cpuspeed

- platform: command_line
  name: CPU Temperature
  command: 'cat /sys/class/thermal/thermal_zone0/temp'
  unit_of_measurement: '°C'
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: fastdotcom
  minute:
    - 0
    - 30

- platform: speedtest
  minute:
    - 15
    - 45
  monitored_conditions:
    - ping
    - download
    - upload

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: processor_use
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: last_boot
    - type: ipv4_address
      arg: eth0

- platform: dnsip
  scan_interval: 1200
