- platform: template
  sensors:
    template_smoke_sensor_livingroom:
      friendly_name: 'Røykvarsler'
      value_template: >-
        {% if is_state("binary_sensor.smoke_sensor_livingroom_alarm_level", "255") %}
          Alarm
        {% elif is_state("binary_sensor.smoke_sensor_livingroom_burglar", "3") %}
          Ikke montert
        {% else %}
          Standby
        {% endif %}

- platform: template
  sensors:
    template_flood_sensor_bathroom:
      friendly_name: 'Vannsensor'
      value_template: >-
        {% if is_state("binary_sensor.flood_sensor_bathroom_alarm_level", "255") %}
          Alarm
        {% elif is_state("binary_sensor.flood_sensor_bathroom_burglar", "3") %}
          Ikke montert
        {% else %}
          Standby
        {% endif %}

- platform: template
  sensors:
    template_magnet_door_main:
      value_template: '{% if is_state("binary_sensor.magnet_door_main", "off") %}Lukket{% else %}Åpen{% endif %}'
      friendly_name: 'Ytterdør'

- platform: template
  sensors:
    template_motion_hall:
      value_template: '{% if is_state("binary_sensor.motion_hall", "off") %}Ingen{% else %}Bevegelse{% endif %}'
      friendly_name: 'Bevegelse (Gang)'
