- alias: Adjust livingroom light color temperature
  trigger:
    platform: state
    entity_id: input_number.livingroom_color_temp
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom
        color_temp: "{{ trigger.to_state.state | int }}"

- alias: Adjust bedroom light color temperature
  trigger:
    platform: state
    entity_id: input_number.bedroom_color_temp
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom
        color_temp: "{{ trigger.to_state.state | int }}"
