- alias: Set livingroom light scene
  trigger:
    platform: state
    entity_id: input_select.livingroom_hue_scene
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Living Room"
        scene_name: "{{ trigger.to_state.state }}"

- alias: Set bedroom light scene
  trigger:
    platform: state
    entity_id: input_select.bedroom_hue_scene
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Bedroom"
        scene_name: "{{ trigger.to_state.state }}"
