- alias: Adjust livingroom light color temperature
  trigger:
    platform: state
    entity_id: input_number.livingroom_color_temp
  action:
    - service: light.turn_on
      data:
        entity_id: light.living_room
        color_temp: "{{ trigger.to_state.state | int }}"

- alias: Adjust bedroom light color temperature
  trigger:
    platform: state
    entity_id: input_number.bedroom_color_temp
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom
        color_temp: "{{ trigger.to_state.state | int }}"

- alias: Set livingroom light scene
  trigger:
    platform: state
    entity_id: input_select.livingroom_hue_scene
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Living Room"
        scene_name: "{{ trigger.to_state.state }}"

- alias: Set bedroom light scene
  trigger:
    platform: state
    entity_id: input_select.bedroom_hue_scene
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Bedroom"
        scene_name: "{{ trigger.to_state.state }}"
