- alias: 'Livingroom light on at sunset'
  initial_state: 'on'
  trigger:
  - platform: sun
    event: sunset
    offset: '-00:30:00'
  condition:
  - condition: state
    entity_id: input_boolean.home
    state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.power_livingroom_light

- alias: 'Outside light on at sunset'
  initial_state: 'on'
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: state
    entity_id: input_boolean.home
    state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.power_outside_lights

- alias: 'Hall light on when movement'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_hall
    to: 'on'
  condition:
  - condition: sun
    after: sunset
    after_offset: "-1:00:00"
  - condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.home
        state: 'on'
      - condition: state
        entity_id: input_boolean.sleep
        state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.power_hall_light

- alias: 'Hall light off when no movement'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_hall
    to: 'off'
    for:
      minutes: 10
  condition:
  - condition: sun
    after: sunset
    after_offset: "-1:00:00"
  action:
  - service: switch.turn_on
    entity_id: switch.power_hall_light

- alias: 'Hall light on when opening front door'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.magnet_door_main
    to: 'on'
  condition:
  - condition: sun
    after: sunset
    after_offset: "-1:00:00"
  action:
  - service: switch.turn_on
    entity_id: switch.power_hall_light
