- alias: 'Livingroom light on at sunset'
  initial_state: 'on'
  trigger:
  - platform: sun
    event: sunset
    offset: '-00:30:00'
  condition:
  - condition: state
    entity_id: input_boolean.home
    state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.power_livingroom_light

- alias: 'Outside light on at sunset'
  initial_state: 'on'
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: state
    entity_id: input_boolean.home
    state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.power_outside_lights
