- alias: 'High CO2 levels'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.netatmo_bedroom_co2
      above: 2000
    - platform: numeric_state
      entity_id: sensor.netatmo_living_room_co2
      above: 2000
  action:
    - service: notify.default
      data:
        message: 'CO2 has passed 2000 ppm...'
        title: 'High indoor CO2 level!'

- alias: 'High freezer temperature'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.thermometer_freezer_temperature
      above: -10
  action:
    - service: notify.default
      data:
        message: 'Freezer above -10 degrees...'
        title: 'Freezer is too hot!'

- alias: 'Low inside temperature'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.smoke_sensor_livingroom_temperature
      below: 12
    - platform: numeric_state
      entity_id: sensor.netatmo_living_room_temperature
      below: 12
  action:
    - service: notify.default
      data:
        message: 'Temperature below 12 degrees...'
        title: 'Low indoor temperature!'

- alias: 'High inside temperature'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.smoke_sensor_livingroom_temperature
      above: 30
    - platform: numeric_state
      entity_id: sensor.netatmo_living_room_temperature
      above: 35
  action:
    - service: notify.default
      data:
        message: 'Temperature above 30 degrees...'
        title: 'High indoor temperature!'

- alias: 'Public IP change'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.myip
  action:
    - service: notify.default
      data_template:
        message: 'Public IP has changed: {{ trigger.to_state.state }}'
        title: 'Public IP changed!'
