- alias: 'REST set sensor data'
  initial_state: 'on'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: sensor.netatmo_bedroom_temperature, sensor.netatmo_outside_temperature, sensor.smoke_sensor_livingroom_temperature
  - platform: state
    entity_id: sensor.flood_sensor_bathroom_temperature, sensor.motion_hall_temperature, sensor.thermometer_storeroom_temperature, sensor.thermometer_office_temperature
  - platform: state
    entity_id: sensor.power_livingroom_tv_power_2, sensor.power_office_pc_power_2
  - platform: state
    entity_id: sun.sun
    to: above_horizon
  - platform: state
    entity_id: sun.sun
    to: below_horizon
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state != "unavailable" }}'
  - condition: template
    value_template: '{{ trigger.from_state.state != "unavailable" }}'
  action:
  - service: rest_command.tomlin_sensor
    data_template:
      action: 'set'
      sensor: '{{ trigger.to_state.object_id }}'
      value: '{{ trigger.to_state.state }}'

#- alias: 'REST update sensor data'
#  initial_state: 'on'
#  hide_entity: true
#  trigger:
#  - platform: state
#    entity_id: sensor.power_livingroom_tv_power_2, sensor.power_office_pc_power_2
#  - platform: sun
#    event: sunset
#  - platform: sun
#    event: sunrise
#  action:
#  - service: rest_command.tomlin_sensor
#    data_template:
#      action: 'update'
#      sensor: '{{ trigger.to_state.object_id }}'
#      value: '{{ trigger.to_state.state }}'
