- alias: 'REST update temperatures'
  initial_state: 'on'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: sensor.netatmo_bedroom_temperature
  - platform: state
    entity_id: sensor.smoke_sensor_livingroom_temperature
  action:
  - service: rest_command.tomlin_update_sensor
    data_template:
      sensor: '{{ trigger.entity_id }}'
      value: '{{ trigger.to_state.state }}'
