- alias: 'Set theme on startup'
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: frontend.set_theme
    data:
      name: midnight

- alias: 'Set away status on startup'
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.away

- alias: 'Set climate temperature on startup'
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heater_l
          - climate.heater_r
      data:
        temperature: 12
        hvac_mode: 'off'

- alias: 'Notification on restart'
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.default
      data:
        message: "Home Assistant has been restarted"
        title: "Restart"
