- alias: 'Home mode'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
      - input_boolean.home
      - switch.telldus_home
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id:
      - input_boolean.sleep
      - input_boolean.away
      - input_boolean.vacation
  - service: switch.turn_off
    entity_id:
      - switch.telldus_sleep
      - switch.telldus_away
  - service: climate.set_hvac_mode
    entity_id: climate.termostat_stue
    data:
      hvac_mode: 'heat'
  - service: climate.set_preset_mode
    entity_id: climate.termostat_stue
    data:
      preset_mode: 'none'

- alias: 'Home mode (at night)'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
      - input_boolean.home
      - switch.telldus_home
    from: 'off'
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-1:00:00'
      - condition: sun
        before: sunrise
  action:
  - service: switch.turn_on
    entity_id:
      - switch.power_outside_lights
      - switch.power_livingroom_sofa
      - switch.power_livingroom_cabinet
  - service: light.turn_on
    entity_id:
      - light.living_room

- alias: 'Sleep mode'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
      - input_boolean.sleep
      - switch.telldus_sleep
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id:
      - input_boolean.home
      - input_boolean.away
      - input_boolean.vacation
  - service: switch.turn_off
    entity_id:
      - switch.telldus_home
      - switch.telldus_away
      - switch.power_livingroom_sofa
      - switch.power_livingroom_cabinet
      - switch.power_hall_light
      - switch.power_outside_lights
  - service: light.turn_off
    entity_id:
      - light.living_room
  - service: light.turn_on
    entity_id:
      - light.nightstand
  - service: climate.set_preset_mode
    entity_id: climate.termostat_stue
    data:
      preset_mode: 'away'

- alias: 'Away mode'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
      - input_boolean.away
      - switch.telldus_away
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id:
      - input_boolean.home
      - input_boolean.sleep
      - input_boolean.vacation
  - service: switch.turn_off
    entity_id:
      - switch.telldus_home
      - switch.telldus_sleep
      - switch.power_bedroom_charger
      - switch.power_bedroom_charger_2
      - switch.power_livingroom_sofa
      - switch.power_livingroom_cabinet
      - switch.power_hall_light
      - switch.power_outside_lights
  - service: light.turn_off
    entity_id:
      - light.living_room
      - light.bedroom
      - light.nightstand
  - service: climate.set_preset_mode
    entity_id: climate.termostat_stue
    data:
      preset_mode: 'away'

- alias: 'Vacation mode'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_boolean.vacation
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id:
      - input_boolean.home
      - input_boolean.sleep
      - input_boolean.away
  - service: switch.turn_off
    entity_id:
      - switch.telldus_home
      - switch.telldus_sleep
      - switch.telldus_away
      - switch.power_bedroom_charger
      - switch.power_bedroom_charger_2
      - switch.power_hall_light
      - switch.power_livingroom_tv
      - switch.power_livingroom_sofa
      - switch.power_livingroom_cabinet
      - switch.power_livingroom_heater_left
      - switch.power_livingroom_heater_right
      - switch.power_office_pc
      - switch.power_outside_lights
  - service: light.turn_off
    entity_id:
      - light.living_room
      - light.bedroom
      - light.nightstand
      - light.other
  - service: climate.set_hvac_mode
    entity_id: climate.termostat_stue
    data:
      hvac_mode: 'off'

- alias: 'Set sleep mode at night'
  initial_state: 'on'
  trigger:
  - platform: time
    at: '01:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.home
    state: 'on'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.sleep
  - service: switch.turn_on
    entity_id: switch.telldus_sleep
