- alias: 'Home mode'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - input_boolean.home
      from: 'off'
      to: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.sleep
        - input_boolean.away
        - input_boolean.vacation
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heater_l
          - climate.heater_r
      data:
        temperature: 18
        hvac_mode: heat

- alias: 'Home mode (at night)'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - input_boolean.home
      from: 'off'
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-1:00:00'
      - condition: sun
        before: sunrise
  action:
    - service: switch.turn_on
      entity_id:
        - switch.power_outside_lights
        - switch.power_sofa
    - service: light.turn_on
      entity_id:
        - light.living_room
        - light.hall_cabinet

- alias: 'Sleep mode'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - input_boolean.sleep
      from: 'off'
      to: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.home
        - input_boolean.away
        - input_boolean.vacation
    - service: switch.turn_off
      entity_id:
        - switch.power_sofa
        - switch.power_outside_lights
    - service: light.turn_off
      entity_id:
        - light.living_room
        - light.hall_cabinet
    - service: light.turn_on
      entity_id:
        - light.nightstand
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heater_l
          - climate.heater_r
      data:
        temperature: 14
        hvac_mode: heat

- alias: 'Away mode'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - input_boolean.away
      from: 'off'
      to: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.home
        - input_boolean.sleep
        - input_boolean.vacation
    - service: switch.turn_off
      entity_id:
        - switch.charger_ben
        - switch.charger_kristin
        - switch.power_sofa
        - switch.power_outside_lights
    - service: light.turn_off
      entity_id:
        - light.living_room
        - light.bedroom
        - light.nightstand
        - light.hall
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heater_l
          - climate.heater_r
      data:
        temperature: 12
        hvac_mode: heat

- alias: 'Vacation mode'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.vacation
      from: 'off'
      to: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.home
        - input_boolean.sleep
        - input_boolean.away
    - service: switch.turn_off
      entity_id:
        - switch.charger_ben
        - switch.charger_kristin
        - switch.power_tv
        - switch.power_pc
        - switch.power_sofa
        - switch.power_outside_lights
    - service: light.turn_off
      entity_id:
        - light.living_room
        - light.bedroom
        - light.nightstand
        - light.hall
        - light.other
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heater_l
          - climate.heater_r
      data:
        temperature: 12
        hvac_mode: 'off'

- alias: 'Set sleep mode at night'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '01:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.home
      state: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.sleep
