- alias: 'Home mode'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_boolean.home
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id:
      - input_boolean.sleep
      - input_boolean.away
      - input_boolean.vacation
  - service: climate.set_operation_mode
    entity_id: climate.termostat_stue
    data:
      operation_mode: 'heat'
  - service: climate.set_away_mode
    entity_id: climate.termostat_stue
    data:
      away_mode: false

- alias: 'Sleep mode'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_boolean.sleep
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id:
      - input_boolean.home
      - input_boolean.away
      - input_boolean.vacation
  - service: switch.turn_off
    entity_id:
      - switch.power_bedroom_charger
      - switch.power_bedroom_light
      - switch.power_hall_light
      - switch.power_livingroom_sofa
      - switch.power_livingroom_light
      - switch.power_outside_lights
  - service: climate.set_away_mode
    entity_id: climate.termostat_stue
    data:
      away_mode: true

- alias: 'Away mode'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_boolean.away
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id:
      - input_boolean.home
      - input_boolean.sleep
      - input_boolean.vacation
  - service: switch.turn_off
    entity_id:
      - switch.power_bedroom_charger
      - switch.power_bedroom_light
      - switch.power_hall_light
      - switch.power_livingroom_sofa
      - switch.power_livingroom_light
      - switch.power_outside_lights
  - service: climate.set_away_mode
    entity_id: climate.termostat_stue
    data:
      away_mode: true

- alias: 'Vacation mode'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_boolean.vacation
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id:
      - input_boolean.home
      - input_boolean.sleep
      - input_boolean.away
  - service: switch.turn_off
    entity_id:
      - switch.power_bedroom_charger
      - switch.power_bedroom_light
      - switch.power_hall_light
      - switch.power_livingroom_tv
      - switch.power_livingroom_sofa
      - switch.power_livingroom_light
      - switch.power_livingroom_heater_left
      - switch.power_livingroom_heater_right
      - switch.power_office_pc
      - switch.power_outside_lights
  - service: climate.set_operation_mode
    entity_id: climate.termostat_stue
    data:
      operation_mode: 'off'

- alias: 'Set sleep mode at night'
  initial_state: 'on'
  trigger:
  - platform: time
    at: '01:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.home
    state: 'on'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.sleep
