- alias: 'Disable other status when Home is enabled'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_boolean.home
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id:
      - input_boolean.sleep
      - input_boolean.away
      - input_boolean.vacation

- alias: 'Disable other status when Sleep is enabled'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_boolean.sleep
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id:
      - input_boolean.home
      - input_boolean.away
      - input_boolean.vacation

- alias: 'Disable other status when Away is enabled'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_boolean.away
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id:
      - input_boolean.home
      - input_boolean.sleep
      - input_boolean.vacation

- alias: 'Disable other status when Vacation is enabled'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_boolean.vacation
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id:
      - input_boolean.home
      - input_boolean.sleep
      - input_boolean.away
